apiVersion: apps/v1
kind: Deployment
metadata:
        name: pihole
        namespace: pihole
        labels:
                app: pihole
                owner: nestor
        annotations:
                application: pihole
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: pihole
        template:
                metadata:
                        name: pihole
                        namespace: pihole
                        labels:
                                app: pihole
                                owner: nestor
                spec:
                        hostname: pihole
                        volumes:
                                - name: "pihole-data"
                                  persistentVolumeClaim:
                                    claimName: pihole-data-nfs
                                - name: "pihole-dnsmasq"
                                  persistentVolumeClaim:
                                    claimName: pihole-dnsmasq-nfs
                        dnsConfig:
                                nameservers:
                                        - 127.0.0.1
                                        - 1.1.1.1
                        containers:
                                - name: pihole
                                  image: pihole/pihole:latest
                                  ports:
                                          - containerPort: 80
                                          - containerPort: 53
                                          - containerPort: 443
                                          - containerPort: 67
                                  volumeMounts:
                                          - mountPath: "/etc/pihole/"
                                            name: "pihole-data"
                                          - mountPath: "/etc/dnsmasq.d/"
                                            name: "pihole-dnsmasq"
                                  env:
                                          - name: TZ
                                            value: "America/Mexico_City"
                                          - name: WEBPASSWORD
                                            valueFrom:
                                              secretKeyRef:
                                                key: PIHOLE_PWD
                                                name: pihole
                                  resources:
                                          limits:
                                                  cpu: "200m"
                                                  memory: "256Mi"
                                          requests:
                                                  cpu: "10m"
                                                  memory: "30Mi"
