apiVersion: apps/v1
kind: Deployment
metadata:
        name: pihole
        labels:
                app: pihole
                owner: nestor
        annotations:
                application: pihole
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: pihole
        template:
                metadata:
                        labels:
                                app: pihole
                                owner: nestor
                spec:
                        volumes:
                                - name: "pihole"
                                  hostPath:
                                        path: "/opt/pihole/etc/pihole/"
                                - name: "dnsmasq"
                                  hostPath:
                                        path: "/opt/pihole/etc/dnsmasq.d/"
                                        #hostname: "pi.hole"
                        dnsConfig:
                                nameservers:
                                 - 127.0.0.1
                                 - 1.1.1.1
                        containers:
                                - name: pihole
                                  image: pihole/pihole
                                  ports:
                                  - containerPort: 80
                                  - containerPort: 53
                                  - containerPort: 443
                                  - containerPort: 67
                                  volumeMounts:
                                        - mountPath: "/etc/pihole/"
                                          name: "pihole"
                                        - mountPath: "/etc/dnsmasq.d/"
                                          name: "dnsmasq"
                                  env:
                                        - name: VIRTUAL_HOST
                                          value: "pi.hole"
                                        - name: PROXY_LOCATION
                                          value: "pi.hole"
                                        - name: ServerIP
                                          value: "127.0.0.1"
                                        - name: TZ
                                          value: "America/Mexico_City"
                                        - name: WEBPASSWORD
                                          value: "pwd"
                                  resources:
                                        limits:
                                                cpu: "200m"
                                                memory: "256Mi"
                                        requests:
                                                cpu: "10m"
                                                memory: "30Mi"
