---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-data-nfs
  namespace: pihole
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-nas"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-dnsmasq-nfs
  namespace: pihole
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-nas"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi