apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - protocol: UDP
      name: dns
      port: 53
      targetPort: 53
  type: LoadBalancer
  externalTrafficPolicy: Local
