apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: dns
      port: 53
      targetPort: 53
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
  externalTrafficPolicy: Local
